print('Seno, Cosseno e Tangente')
print()
import math
an = float(input('Digite o valor do ângulo: '))
se = math.sin(math.radians(an))
print('O ângulo de {}ºG tem o seno de {:.2f}ºG.'.format(an, se))
coss = math.cos(math.radians(an))
print('O ângulo de {}ºG tem a cosseno de {:.2f}ºG.'.format(an, coss))
tan = math.tan(math.radians(an))
print('O ângulo de {}ºG tem a tangente de {:.2f}ºG.'.format(an, tan))
print('')
from math import sin, cos, tan, radians
an = float(input('Digite o valor do ângulo: '))
se = sin(radians(an))
print('O ângulo {}ºG tem o seno de {:.2f}ºG.'.format(an, se))
coss = cos(radians(an))
print('O ângulo de {}ºG tem o cosseno de {:.2f}ºG.'.format(an, coss))
tang = tan(radians(an))
print('O ângulo de {}ºG tem a tangente de {:.2f}ºG.'.format(an, tang))
